apiVersion: v1
kind: Service
metadata:
  name: travel-agency-service
  namespace: travel-agency
spec:
  type: NodePort
  selector:
    app: travel-agency
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
